// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asdasibdycafhqywsuvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzZGFzaWJkeWNhZmhxeXdzdXZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI4NjgzNjIsImV4cCI6MjA0ODQ0NDM2Mn0.7fwhwV8VpahuhEs_VhO1eI49TOmZ_BBOEWLhJHvohvE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);